apiVersion: batch/v1
kind: Job
metadata:
  name: demo-job
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: curl
          image: curlimages/curl:8.7.1
          args: ["-sS", "http://echo-svc"]
  backoffLimit: 1